#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Daniel Radman
# SPDX-License-Identifier: MIT
# provision-python3-shim.sh — make the literal command `python3` resolve on a host
# (typically a stock Windows / Git-Bash install) where Python exists only as `python`
# and/or the `py -3` launcher and there is no `python3` on PATH.
#
# PRFlow's shell helpers, the agent-typed `python3 <path>` local-tier convention, and the
# cloud `Bash(python3:*)` allowlist all invoke the literal `python3`. A shell resolver
# inside our helpers cannot intercept the agent-typed commands or the allowlist, so the
# literal `python3` must actually resolve. A single consent-gated `python3` shim on PATH is
# the one intervention that makes every class work at the root, with no call-site churn.
#
# Interpreter selection is centralized in lib/resolve-python.sh (the single source of
# truth, shared with preflight.sh): the FIRST of `python3`, `py -3`, `python` reporting
# sys.version_info >= (3, 11). The shim execs that resolved ALTERNATE (never `python3` —
# that would recurse into the shim) and forwards "$@" + the exit code.
#
# CONSENT: writing a shim into a user PATH directory mutates the user's environment, so
# (mirroring scripts/provision-auto-mode.sh) the DEFAULT (no --apply) prints exactly what
# it WOULD do and writes NOTHING; --apply performs the write. The user re-runs with --apply
# to opt in. install.sh surfaces this provisioner in plan-only mode (no --apply); /devflow:init
# surfaces it indirectly by relaying preflight's pointer (preflight.sh emits it when python3 is
# absent but a >=3.11 alternate exists).
#
# Idempotent: when a working `python3 >=3.11` already resolves (including via a shim a
# previous run installed), it is a no-op that exits 0 with a "nothing to do" breadcrumb.
# Refuses (non-zero) when no >=3.11 interpreter exists — it never writes a broken shim, and
# it never overwrites a `python3` it did not itself create.
#
# Usage: provision-python3-shim.sh [--apply] [TARGET_DIR]
#   --apply     perform the write (the caller's confirmed consent). Without it, print the
#               plan + manual instructions, exit 0, touch nothing.
#   TARGET_DIR  directory to write the shim into (default: the first writable directory
#               already on PATH, else ~/bin with a PATH note). Exists mainly for tests;
#               production omits it.
#
# Exit codes:
#   0  printed the plan (no --apply); provisioned the shim (--apply); or a no-op because
#      `python3 >=3.11` already resolves.
#   2  a malformed invocation (unknown option / extra arg / empty target); OR no >=3.11
#      interpreter exists (refuse — never write a broken shim); OR (--apply) no writable
#      directory on PATH and HOME is unset, so no shim location can be chosen; OR (--apply)
#      the chosen shim path is an existing non-PRFlow `python3`, or the directory/file
#      could not be created or written. In every exit-2 case nothing is written and a
#      specific `devflow-python:` breadcrumb names the cause.
#   3  (--apply, auto-selected PATH dir) the shim WAS written, but an earlier PATH entry holds
#      a foreign/broken/older `python3` that shadows it, so `python3` still does not resolve to
#      the shim. Distinct from exit 2 (which writes nothing): here the shim exists but does not
#      yet win on PATH; the breadcrumb names the shadowing path and the remedy.
set -euo pipefail

log()  { printf 'devflow-python: %s\n' "$1"; }
warn() { printf 'devflow-python: %s\n' "$1" >&2; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/resolve-python.sh
. "$SCRIPT_DIR/../lib/resolve-python.sh"

# Marker line written into every PRFlow shim, used to recognize our own shim on a re-run
# so we never overwrite an unrelated `python3` the user placed on PATH.
SHIM_MARKER='Generated by DevFlow scripts/provision-python3-shim.sh'

# ── Parse args: an optional --apply flag and at most one positional target dir. ──
APPLY=0
TARGET_DIR=""
TARGET_GIVEN=0
for arg in "$@"; do
  case "$arg" in
    --apply) APPLY=1 ;;
    -*)      warn "unknown option: $arg"; exit 2 ;;
    *)       if [ "$TARGET_GIVEN" -eq 1 ]; then
               warn "unexpected extra argument: $arg"; exit 2
             fi
             if [ -z "$arg" ]; then
               warn "empty target directory argument; provisioned nothing (pass a real path or omit it)."
               exit 2
             fi
             TARGET_GIVEN=1
             TARGET_DIR="$arg" ;;
  esac
done

# ── Resolve the interpreter (shared contract). ──
# rc 0 → a >=3.11 invocation; rc 1 → a runnable interpreter exists but all are <3.11 (the
# echoed value is the first runnable one, for the version message); rc 3 → none runs.
RESOLVED=""
RC=0
RESOLVED="$(devflow_resolve_python)" || RC=$?

if [ "$RC" -eq 3 ]; then
  warn "no Python interpreter found on PATH (looked for python3, 'py -3', python). Install Python 3.11 or newer, then re-run."
  exit 2
fi
if [ "$RC" -eq 1 ]; then
  # shellcheck disable=SC2086  # $RESOLVED is an invocation that may be the two words "py -3"
  warn "the only Python found ($RESOLVED -> $($RESOLVED -V 2>&1)) is older than 3.11; refusing to write a shim. Install Python 3.11 or newer, then re-run."
  exit 2
fi

# rc 0. If `python3` itself already resolves to >=3.11 (incl. a shim a prior run wrote, or
# a real macOS/Linux python3), there is nothing to do — idempotent no-op.
if [ "$RESOLVED" = "python3" ]; then
  log "a working 'python3' (>=3.11) is already on PATH; nothing to do."
  exit 0
fi

# An alternate (>=3.11) interpreter resolved: $RESOLVED is "py -3" or "python".
SHIM_NAME="python3"

# ── DEFAULT (no consent): describe the action and write NOTHING. ──
if [ "$APPLY" -ne 1 ]; then
  log "found a compatible Python (>=3.11) as '$RESOLVED' but no 'python3' on PATH."
  log "To make every literal 'python3' call resolve, PRFlow can install a small '$SHIM_NAME' shim (exec $RESOLVED \"\$@\") into a writable directory on your PATH."
  log "Re-run with explicit consent to have PRFlow write it: provision-python3-shim.sh --apply"
  log "Or add it yourself: create an executable '$SHIM_NAME' on your PATH containing: exec $RESOLVED \"\$@\""
  exit 0
fi

# ── --apply (consent confirmed): choose a target directory and write the shim. ──
PATH_NOTE=0
if [ -z "$TARGET_DIR" ]; then
  # Prefer the first WRITABLE directory already on PATH — a shim there needs no PATH note.
  # `set -f` disables pathname (glob) expansion for the split: without it, a PATH entry
  # containing a glob metacharacter (`*`/`?`/`[`) would be expanded against the filesystem
  # and select the wrong TARGET_DIR (or, on no match, the literal). We want the split to
  # depend only on the literal PATH contents. Restore the prior glob state afterward.
  _oldifs="$IFS"
  case "$-" in *f*) _hadf=1 ;; *) _hadf=0 ;; esac
  set -f
  IFS=':'
  for d in $PATH; do
    [ -n "$d" ] || continue
    if [ -d "$d" ] && [ -w "$d" ]; then
      TARGET_DIR="$d"
      break
    fi
  done
  IFS="$_oldifs"
  [ "$_hadf" -eq 1 ] || set +f
  if [ -z "$TARGET_DIR" ]; then
    # Fall back to the standard Git-Bash ~/bin (its default profile adds ~/bin to PATH when
    # the directory exists). Surface a PATH note since we cannot confirm it is on PATH.
    if [ -z "${HOME:-}" ]; then
      warn "no writable directory on PATH and HOME is unset; cannot choose a shim location. Re-run with an explicit TARGET_DIR that is on your PATH."
      exit 2
    fi
    TARGET_DIR="$HOME/bin"
    PATH_NOTE=1
  fi
fi

SHIM="$TARGET_DIR/$SHIM_NAME"

# Never clobber a `python3` PRFlow did not create. (A real working python3 would have
# short-circuited above; this guards the edge where a <3.11 `python3` lives in the chosen
# dir, or the user placed their own wrapper there.) A PRFlow shim from a prior run is
# safe to rewrite — recognized by the marker line. The `-L` arm is load-bearing: `-e`
# follows symlinks and reports a DANGLING `python3` symlink as non-existent, so without it
# the guard would skip and `mv` would silently replace a symlink PRFlow did not create —
# and a dangling/broken `python3` symlink is exactly the corrupt-interpreter class this
# targets, so it must hit the refuse branch (the marker grep on a dangling link fails to
# read → `! grep` true → refuse), not fall through.
if { [ -e "$SHIM" ] || [ -L "$SHIM" ]; } && ! grep -q "$SHIM_MARKER" "$SHIM" 2>/dev/null; then
  warn "refusing to overwrite an existing $SHIM that PRFlow did not create; remove it yourself or pass a different TARGET_DIR on your PATH."
  exit 2
fi

mkdir -p "$TARGET_DIR" || { warn "could not create $TARGET_DIR; wrote no shim."; exit 2; }
TMP="$(mktemp "$TARGET_DIR/.python3-shim.XXXXXX")" || { warn "could not create a temp file in $TARGET_DIR; wrote no shim."; exit 2; }
trap 'rm -f "$TMP"' EXIT
# The shim execs the resolved ALTERNATE directly (never python3) so it cannot recurse into
# itself; `exec` replaces the process, so the alternate's exit code forwards unchanged.
# Capture the status rather than negating the compound with `if ! { … } > "$TMP"`: bash
# does not propagate a failed redirect on a compound command through `!` (issue #1524), so
# the negated form reported the shim written when the body never landed.
shim_write_rc=0
{
  printf '#!/usr/bin/env bash\n'
  printf '# %s — forwards to the resolved Python (%s).\n' "$SHIM_MARKER" "$RESOLVED"
  printf '# Execs the alternate interpreter directly (never python3) so it cannot recurse.\n'
  printf 'exec %s "$@"\n' "$RESOLVED"
} > "$TMP" || shim_write_rc=$?
if [ "$shim_write_rc" -ne 0 ]; then
  warn "could not write the shim body to $TMP; wrote no shim."
  exit 2
fi
chmod +x "$TMP" || { warn "could not make the shim executable; wrote no shim."; exit 2; }
mv "$TMP" "$SHIM" || { warn "could not place the shim at $SHIM; wrote no shim."; exit 2; }
trap - EXIT

# Report the outcome. We only CLAIM "python3 now resolves" when we can actually confirm it —
# i.e. when we AUTO-SELECTED a writable directory already on this shell's PATH (TARGET_GIVEN=0
# and no ~/bin fallback). The write path is reached whenever no working `python3 >=3.11`
# resolves (it is absent, present-but-broken, or too old — RESOLVED is then an alternate). The
# EXIT-3 shadow outcome is the subset where a non-working `python3` still sits in an EARLIER
# PATH directory and shadows the shim we wrote into a later writable dir — in which case
# `python3` still resolves to the broken/old interpreter and an unconditional success claim
# would be false (the most confusing outcome: the tool says "fixed", the user re-runs preflight
# and hits the same failure). When `python3` was fully absent, nothing shadows the shim and it
# wins. Verify the postcondition before asserting it; `hash -r` first so the lookup reflects the
# on-disk PATH, not a candidate the resolver may have hashed earlier.
if [ "$TARGET_GIVEN" -eq 0 ] && [ "$PATH_NOTE" -eq 0 ]; then
  hash -r 2>/dev/null || true
  _resolved_now="$(command -v python3 2>/dev/null || true)"
  if [ "$_resolved_now" = "$SHIM" ]; then
    log "provisioned $SHIM (exec $RESOLVED \"\$@\"): the literal 'python3' command now resolves to your >=3.11 Python."
  else
    # The shim went into a writable PATH dir, but `python3` still resolves elsewhere (or
    # nowhere): an earlier PATH entry holds a foreign/broken/older `python3` that shadows it.
    # Do NOT claim "now resolves" — name the shadowing path and the remedy, and exit non-zero
    # (distinct code 3: the shim WAS written, unlike the exit-2 "wrote nothing" refusals) so a
    # caller and the user can tell the provision did not achieve its goal.
    warn "provisioned $SHIM, but 'python3' still resolves to '${_resolved_now:-nothing}' — an earlier PATH entry shadows the shim. Remove or repair that python3, or move $TARGET_DIR earlier on your PATH, then re-run 'bash lib/preflight.sh'."
    exit 3
  fi
else
  # Explicit TARGET_DIR, or the ~/bin fallback: we cannot confirm the dir is on THIS shell's
  # PATH, so we do not claim "now resolves" — we report the write and (on the fallback) how to
  # activate it. The user's preflight re-run is the real confirmation.
  log "provisioned $SHIM (exec $RESOLVED \"\$@\")."
  if [ "$PATH_NOTE" -eq 1 ]; then
    log "NOTE: $TARGET_DIR may not be on your PATH. Git-Bash's default profile adds ~/bin when it exists; if 'python3 --version' still fails, add $TARGET_DIR to your PATH (e.g. add 'export PATH=\"\$HOME/bin:\$PATH\"' to ~/.bashrc) and reopen the shell."
  fi
fi
exit 0
